services:
    ivypatroni1:
        image: ivorysql/docker-compose-ha-cluster:4.6-4.0.6-ubi8
        restart: always
        container_name: ivyhac1
        user: "ivorysql"
        environment:
            PATRONI_SCOPE: ivory-cluster
            ETCD_HOSTS: etcd1:2379,etcd2:2379,etcd3:2379
            IVORYSQL_PASSWORD: 123456
            IVORYSQL_HOST_AUTH_METHOD: md5
            PATRONI_SERVICE_NAME: ivypatroni1
            IVORYSQL_HOST: ivorysql1
        volumes:
          - /home/ivorysql/patroni:/var/local/ivorysql/ivorysql-4/patroni/
          - /home/ivorysql/ivydata:/var/local/ivorysql/ivorysql-4/data/