services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.8
    container_name: etcd
    environment:
      - ETCD_NAME=etcd3
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://<cluster3_ip>:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://<cluster3_ip>:2379
      - ETCD_LISTEN_PEER_URLS=http://<cluster3_ip>:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://<cluster1_ip>:2380,etcd2=http://<cluster2_ip>:2380,etcd3=http://<cluster3_ip>:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
    network_mode: host
    volumes:
    - /home/ivorysql/etcd:/etcd-data
