# headless service to avoid deletion of ivorysql-patroni-hac-config endpoint
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceConfigName }}
  namespace: {{ .Values.namespace }}
  labels:
    application: {{ .Values.applicationName }}
    cluster-name: {{ .Values.clusterName }}
spec:
  clusterIP: None
  selector:
    application: {{ .Values.applicationName }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseServiceName }}
  namespace: {{ .Values.namespace }}
  labels:
    application: {{ .Values.applicationName }}
    cluster-name: {{ .Values.clusterName }}
spec:
  type: NodePort
  selector:
    application: {{ .Values.applicationName }}
    cluster-name: {{ .Values.clusterName }}
    role: primary
  ports:
  - protocol: TCP
    name: ivorysql
    port: 5432
    targetPort: 5432
  - protocol: TCP
    name: ivorysql-oracle
    port: 1521
    targetPort: 1521

#    nodePort: {{ .Values.port.dbPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ivyHacReplicaServiceName }}
  namespace: {{ .Values.namespace }}
  labels:
    application: {{ .Values.applicationName }}
    cluster-name: {{ .Values.clusterName }}
    role: replica
spec:
  type: NodePort
  selector:
    application: {{ .Values.applicationName }}
    cluster-name: {{ .Values.clusterName }}
    role: replica
  ports:
  - protocol: TCP
    name: ivorysql
    port: 5432
    targetPort: 5432
  - protocol: TCP
    name: ivorysql-oracle
    port: 1521
    targetPort: 1521
#    nodePort: {{ .Values.port.dbReplPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.podServiceName }}
  namespace: {{ .Values.namespace }}
  labels:
    application: {{ .Values.applicationName }}
    cluster-name: {{ .Values.clusterName }}

spec:
  type: ClusterIP
  selector:
    application: {{ .Values.applicationName }}
    cluster-name: {{ .Values.clusterName }}
  clusterIP: None
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  publishNotReadyAddresses: true
